### ISSUE TITLE
ESC characters spammed in the terminal.

### ISSUE THREAD

**Issue by DougBeney** [spywhere/Terminality#15]
Running on a Mac
<img width="710" alt="screen shot 2016-08-27 at 9 52 14 am" src="https://cloud.githubusercontent.com/assets/19509074/18027838/0cdaa290-6c3c-11e6-8147-1f4758b1d7e7.png">

Love the plugin, but I'm noticing a bunch of "ESC" characters spammed on the screen (as seen in the screenshot). 

Any workaround for this?

**Comment by spywhere** [comment]
Terminality works by dumping the process output (stdout) periodically (depends on `refresh_interval` settings). When the time is out, plugin will write all of these output to the Sublime Text's buffer and there is an issue when the output is not completely finish its sequence (such as unicode character that might larger than one byte) which when write to the Sublime Text's buffer, it will cause those weird characters (`ESC`, `BEL` and such).

What I can suggest is you can try remove those characters by set `encoding_handle` to `ignore`. This will ignore all invalid character sequence that might cause during the process. However, if the process intended to send special characters (such as colour code, or escaped-sequence) those byte will be written to the Sublime Text's buffer as a raw data which might appear as `ESC`.

Hope these information is clear enough for you. If you need more explanation, feels free to let me know.
