### ISSUE TITLE
[Bug] Python 3 output not working

### ISSUE THREAD

**Issue by Kristinita** [spywhere/Terminality#18]
### Summary

I can not run in Python 3.

### Expected behavior

For example, I have file `test.py`. Content of file:

```python
print("Sasha Goddess!")
```

If I run file use command prompt:

```shell
E:\Киролайна>python test.py
Sasha Goddess!
```

If in `test.py` I press <kbd>Ctrl+Shift+P</kbd> → `Terminality: Browse Commands...` → `Run test.py as Python 2.7 document` → new tab was opened for me, I see in new tab:

    Sasha Goddess!

### Actual behavior

I see [mojibake](https://en.wikipedia.org/wiki/Mojibake) if I run any Python script.

    "python3" �� ���� ����७��� ��� ���譥�
    ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

If in `test.py` I press <kbd>Ctrl+Shift+P</kbd> → `Terminality: Browse Commands...` → `Run test.py as Python 3 document` → new tab was opened for me, I see mojibake in new tab.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126
**Python version in operating system:**
3.5.2

Thanks.

**Comment by sirisak-lu** [comment]
Python 3 command will use `python3` executable to run your file. If you already set your executable to be `python` you can simply use Python 2 command to run it.

In another word,
- Python 3 command use `python3` executable to run
- Python 2 command use `python` executable to run
