### ISSUE TITLE
Can't handle output encoding correctly

### ISSUE THREAD

**Issue by utensil** [spywhere/Terminality#2]
![image](https://cloud.githubusercontent.com/assets/64258/7155756/bb950358-e393-11e4-9d54-5d1ce2798890.png)

I'm on a Windows 7 machine(Chinese edition, which uses CP936 i.e. GBK as encoding) with customized `additional_execution_units`:

```
{
    "additional_execution_units": {
        "*": {
            "cmd": {
                "name": "Run Cmd here",
                "description": "Run cmd $nice_parent_name",
                "required": ["parent_relative", "parent"],
                "location": "$parent",
                "command": "cmd",
                "platforms": ["windows"],
                "no_echo": true,
                "macros": {
                    "nice_parent_name": [
                        "at \"$parent_rel\"",
                        "here"
                    ],
                    "parent_rel": [
                        ["$parent_relative", "(\\w+/?)+"]
                    ]
                }
            }
        }
    }
}
```

**Comment by utensil** [comment]
I believe it's caused by https://github.com/spywhere/Terminality/blob/bb8535030168d59b5899b4d0463a452741b76341/generic_shell.py#L67-L77 .

It would be nice if  the encoding can be configured.

**Comment by spywhere** [comment]
Alright, thanks for the pull request. This fix will also included in the Javatar too (it's use the exactly same class).
