### ISSUE TITLE
[Bug] Incorrect output encoding for Cyrillic symbols

### ISSUE THREAD

**Issue by Kristinita** [spywhere/Terminality#20]
### 1. Summary

I get Mojibake instead of Cyrillic symbols in output.

### 2. Settings

I have a file `KristinaFlawless.py` in UTF-8 encoding:

```python
# -*- coding: utf-8 -*-
print("Кристина Безупречна!")
```

### 3. Expected behavior

Output, if I run command in terminal:

```c++
D:\Киролайна>python3 KristinaFlawless.py
Кристина Безупречна!

D:\Киролайна>python3 -u KristinaFlawless.py
Кристина Безупречна!

```

### 4. Actual behavior

Output, if I run command use Terminality:

    �������� ����������!

`"debug": true` for me, I get output in Sublime Text console:

```xml
n<member>\n<name>pep8_ignore</name>\n<value><array><data>\n<value><string>E501</string></value>\n</data></array></value>\n</member>\n<member>\n<name>pyflakes_ignore</name>\n<value><array><data>\n</data></array></value>\n</member>\n</struct></value>\n</param>\n<param>\n<value><string>D:\\\xd0\x9a\xd0\xb8\xd1\x80\xd0\xbe\xd0\xbb\xd0\xb0\xd0\xb9\xd0\xbd\xd0\xb0\\KristinaFlawless.py</string></value>\n</param>\n</params>\n</methodCall>\n'
reply: 'HTTP/1.0 200 OK\r\n'
header: Server header: Date header: Content-type header: Content-length send: b'POST /RPC2 HTTP/1.1\r\nHost: 127.0.0.1:4873\r\nAccept-Encoding: gzip\r\nContent-Type: text/xml\r\nUser-Agent: Python-xmlrpc/3.3\r\nContent-Length: 788\r\n\r\n<?xml version=\'1.0\'?>\n<methodCall>\n<methodName>check_syntax</methodName>\n<params>\n<param>\n<value><string># -*- coding: utf-8 -*-\nprint("\xd0\x9a\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xb8\xd0\xbd\xd0\xb0 \xd0\x91\xd0\xb5\xd0\xb7\xd1\x83\xd0\xbf\xd1\x80\xd0\xb5\xd1\x87\xd0\xbd\xd0\xb0!")\n</string></value>\n</param>\n<param>\n<value><string>UTF-8</string></value>\n</param>\n<param>\n<value><struct>\n<member>\n<name>pep8</name>\n<value><boolean>1</boolean></value>\n</member>\n<member>\n<name>pep8_max_line_length</name>\n<value><int>79</int></value>\n</member>\n<member>\n<name>pep8_ignore</name>\n<value><array><data>\n<value><string>E501</string></value>\n</data></array></value>\n</member>\n<member>\n<name>pyflakes_ignore</name>\n<value><array><data>\n</data></array></value>\n</member>\n</struct></value>\n</param>\n<param>\n<value><string>D:\\\xd0\x9a\xd0\xb8\xd1\x80\xd0\xbe\xd0\xbb\xd0\xb0\xd0\xb9\xd0\xbd\xd0\xb0\\KristinaFlawless.py</string></value>\n</param>\n</params>\n</methodCall>\n'
reply: 'HTTP/1.0 200 OK\r\n'
header: Server header: Date header: Content-type header: Content-length Running "python3 -u D:\Киролайна\KristinaFlawless.py "
Working dir is "D:\Киролайна"
```

### 5. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

<kbd>Ctrl+Shift+P</kbd> → `Terminality: Browse Commands…` → `Run KristinaFlawless.py as python3` → I get actual behavior.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by spywhere** [comment]
Please take a look [here](https://github.com/spywhere/Terminality/issues/2) on how to configure for different encoding.

**Comment by Kristinita** [comment]
@spywhere , yes, I read **#2** issue. It not solved my problem.

1. It for chinese symbols,
2. I want use UTF-8 encoding for output.
3. I don't understand, which actions I need to do, that solved my problem.

Thanks.

**Comment by spywhere** [comment]
You have to set the correct `encoding` value (as you want to use) in the settings.

**Comment by Kristinita** [comment]
I want to use UTF-8.

Thanks.

**Comment by Kristinita** [comment]
@spywhere, usage non UTF-8 encoding not recommended, see [**Why do we need Unicode?**](http://stackoverflow.com/a/15128103/5951529).

And if I use [**SublimeREPL**](https://packagecontrol.io/packages/SublimeREPL): <kbd>Ctrl+Shift+P</kbd> → `SublimeREPL: Python - Run Current File`, I get expected behavior like terminal. I have to use SublimeREPL instead of Terminality.

Thanks.
