### ISSUE TITLE
Does not run Lua.

### ISSUE THREAD

**Issue by jamiecropley** [spywhere/Terminality#22]
I get this issue running even basic lua code, e.g. hello world program on both windows 10 and the latest mac operating system when I run the code in terminality on both operating systems it only gives the following output: 

lua: module '/Users/jamiecropley/Desktop/test.lua' not found:
	no field package.preload['/Users/jamiecropley/Desktop/test.lua']
	no file '/usr/local/share/lua/5.3//Users/jamiecropley/Desktop/test/lua.lua'
	no file '/usr/local/share/lua/5.3//Users/jamiecropley/Desktop/test/lua/init.lua'
	no file '/usr/local/lib/lua/5.3//Users/jamiecropley/Desktop/test/lua.lua'
	no file '/usr/local/lib/lua/5.3//Users/jamiecropley/Desktop/test/lua/init.lua'
	no file './/Users/jamiecropley/Desktop/test/lua.lua'
	no file './/Users/jamiecropley/Desktop/test/lua/init.lua'
	no file '/usr/local/lib/lua/5.3//Users/jamiecropley/Desktop/test/lua.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './/Users/jamiecropley/Desktop/test/lua.so'
	no file '/usr/local/lib/lua/5.3//Users/jamiecropley/Desktop/test.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './/Users/jamiecropley/Desktop/test.so'
stack traceback:
	[C]: in function 'require'
	[C]: in ?

**Comment by spywhere** [comment]
Normally, do you set any command flags when you have to run it yourself? Do you require any file in your script?

**Comment by jamiecropley** [comment]
No, I am using the default build system in sublime text. No the files I am running are without modules. I see why your asking that from the output, and to be honest it makes no sense why it is saying that to me.

**Comment by spywhere** [comment]
I see. Terminality use `lua -l <file name>` as a command (instead of `lua <file name>`) to run. So, to fix this (while waiting for a new update) is to override the command by set the `execution_units` settings (see reference in README file and in [Lua sample](https://github.com/spywhere/Terminality/blob/master/Collections/Lua.terminality-collections)).

**Comment by jamiecropley** [comment]
Sorry, I have no idea what file you are reffering to when you specify to put: `lua -l <file name>` where exactly?

**Comment by spywhere** [comment]
You have to set `execution_units` in your user's settings file. Please see the README for more details on how and what do the settings do.

**Comment by jamiecropley** [comment]
Even in the readme file it does not specify the file of execution_units, which one I need to go into, or do I go into my own custom settings and set my own up for terminality or do I go into the package default for lua and change there? Sorry but it is not clear to me. e.g. you have settings user and settings default for terminality.

**Comment by spywhere** [comment]
There are 3 settings in Sublime Text, default settings (the one shipped with ST itself, read only), user's settings (the one you use to change ST settings and also most of the packages installed, writable, affect the whole ST regardless of the project) and project's settings (the one that saved into `.sublime-project` file, writable, affect only associated projects). You have to set `execution_units` settings either in your project's settings or user's settings to override the default behavior of the package. Hope that clear to you.

**Comment by Some-T** [comment]
ok makes sense now, many thanks.

**Comment by jamiecropley** [comment]
I tried to set this in the preferences settings for user in sublime text, 

![image](https://user-images.githubusercontent.com/17186004/29376388-4c90efe4-82b0-11e7-896f-071c51a74ce8.png)

I get that following error when I try and save the text you indicated from: 

https://github.com/spywhere/Terminality/blob/master/Collections/Lua.terminality-collections

![image](https://user-images.githubusercontent.com/17186004/29376413-619fee26-82b0-11e7-8d1f-83259309ac85.png)

**Comment by spywhere** [comment]
You have to merged those two settings together.

**Comment by jamiecropley** [comment]
I tried to merge those two settings together (the ones on the right-hand side, unfortunately, there was a parse error so that does not work?

**Comment by spywhere** [comment]
Please checkout Sublime Text [official](https://www.sublimetext.com/docs/3/) and [unofficial](http://docs.sublimetext.info/en/latest/index.html) documentation as this does not relevant to this extension anymore.

**Comment by jamiecropley** [comment]
ok thanks.
